CREATE TABLE IF NOT EXISTS groups(
	GID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS permissions(
	PID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(100) NOT NULL,
	description VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS group_permissions(
	GID INT NOT NULL,
	PID INT NOT NULL,
    PRIMARY KEY (GID, PID),
	CONSTRAINT GP_FK_GID FOREIGN KEY (GID) REFERENCES groups (GID),
	CONSTRAINT GP_FK_PID FOREIGN KEY (PID) REFERENCES permissions (PID)
);

CREATE TABLE IF NOT EXISTS user_groups(
	UID INT NOT NULL,
	GID INT NOT NULL,
    PRIMARY KEY (UID, GID),
	CONSTRAINT UG_FK_GID FOREIGN KEY (GID) REFERENCES groups (GID)
);